# (PART) 村民神明信仰 {-}

# 西埠村神明信仰基本状况 {#basic-situation}

根据官方资料与访谈信息，西埠村信仰的神明主要有六位，分别是**茅竹水仙大王、土地公、南村天后、广化马君与广兆泰山**。但实际上村民们还会根据自己的需求信奉村外的其他神明，例如公和祖、南海观音和调旦王。

在西埠村，**"神"亦称作"祖"，"祖"也可以转而称作为"神"**。例如，村民们有时会将茅竹水仙大王直称为"祖"，将南村天后称为"婆祖"，将广化马君称为"马祖"。相应地，家中祭拜的祖先则可以被称作"家神"。

"祖"分为"境祖"与"村祖"，前者受多个村子共同信奉，而后者只为某一村子信奉。在西埠村，只有土地公与茅竹水仙大王属于"村祖"，南村天后、广化马君与广兆泰山等则属于"境祖"。

不同类型的"祖"或"神"在仪式中表现出不同的特点。从时间上来看，境祖在村子之间流动，村主在村内流动；从空间上来看，境祖多为一个月流动一次，村祖四个月流动一次。以茅竹水仙大王为例，只在西埠村头人家中流动，一次停留四个月；马君一个月在受供奉的村子之间流动一次。

西埠村内信仰的神明基本都有神像和庙宇，部分神明还拥有神位、轿子以及推车。村中的茅竹水仙大王与土地公都有属于自己的庙宇，但没有神位，也没有轿子，而没有轿子的神明无法参与到游神仪式中。广化马君与二婆没有属于自己的庙宇和神位，因此必须在不同的村子间流动，到不同的村民家中落座。

<br>

|     神明     | 神格 | 流动时间 | 流动区域 |          神物          |
|:------------:|:----:|:--------:|:--------:|:----------------------:|
| 茅竹水仙大王 | 村祖 |  四个月  |   村内   |       神像、庙宇       |
|    土地公    | 村祖 |  四个月  |   村内   |       神像、庙宇       |
|   南村天后   | 境祖 |  一个月  |   村际   | 神像、神位、庙宇、轿子 |
|   南海观音   | 境祖 |  一个月  |   村际   |          神像          |
|   广化马君   | 境祖 |  一个月  |   村际   |    神像、轿子、车子    |
|   广兆泰山   | 境祖 |  一个月  |   村际   |                        |
|    调旦王    |      |          |          |                        |
|    公和祖    |      |          |          |                        |
|   家中祖先   | 村祖 |  不流动  |  不流动  |          牌位          |

: (#tab:god-in-xibu) 西埠村信仰神明概况

<br>

如同渔民们海上生活的漂泊，神明在村中则经由各种仪式实现流动。仪式有大有小，多元丰富，简单概括可以分为请神、接神、拜神、送神、还福和游神。其中，仪式的时间由神像的类型、节日决定。

请神不具备固定时间点，往往在村民家奉喜事时发起，例如入伙、结婚；接神可分为两类，一类是村民接主动请来的神明，一类是村民按照打飞结果被动接受在上一户人家坐满时间的神明，后者时间由该神明类型决定；拜神时间最为广泛，无论是到头人家中，或是去庙宇，抑或是在任何其他仪式环节上都可以进行祭拜；还福仪式......游神仪式一般在初八到元宵期间进行。

::: {.rmdnote data-latex="{注意}"}
"请神"不等于"接神"。即使一个村子没有人主动请神，但多个村子信奉的神在某个村子坐够一定时间，便需要轮坐到下一个村子。一般通过开飞梁来看到哪个村子，村民也可以主动提名要求。因此，严格上来说，如果没有人愿意主动提名要求请神，飞梁开出以后，神明到某村某户村民落座时，该村民做的是"接神"，而非"请神"。
:::

<br>

| 仪式 |                         时间                         |
|:----:|:----------------------------------------------------:|
| 请神 | 结婚、入伙等喜庆活动/                                |
| 接神 | 结婚、入伙等喜庆活动/打飞开出时间/马君农历十八开始轮 |
| 送神 | 境祖坐满一个月，村祖坐满四个月                       |
| 拜神 | 理论上任何时间都可以                                 |
| 送神 |                                                      |
| 还福 |                                                      |
| 游神 | 初八到元宵期间                                       |

: (#tab:yishitime-in-xibu) 西埠村神明仪式时间表

<br>

## 信仰神明 {#god}

### 茅竹水仙大王 {#maozhu}

硇洲岛上不止一尊水仙大王，各有名号，西埠村供奉的称为茅竹水仙大王。根据村中老人的说法，茅竹水仙大王本体为一尊香炉，从海上飘来西埠，停留在村子内，村民们依据天书为其雕刻真身，并建立露天庙宇。

茅竹水仙大王的神像日常在村民家中轮坐，每四个月轮换一次，一年分为年头、年中、年末三个时间段，分别由一个头人负责看管。神像在头人家受供奉期间，村民或外村人若想祭拜水仙公，皆可携带祭品前往。

由于茅竹水仙大王于正月二十六抵达西埠村，故其诞辰被定为此日。

### 土地公 {#tudigon}

岛上基本每个村子都有属于自己村的土地公，在部分村民眼中，土地公属于本村的村主，管辖与统筹村中所有的事务，无法如同其他神明一般流动到其他村子。

在西埠村，土地公的神像常常随同水仙公的神像一起在不同的村民家中轮坐。

### 南村天后 {#tianhou}

在西埠村，南村天后被认为是妈祖，又称为"南村軍主天后聖母元君"，属南村境内供奉。据专家考证，公元1278年农历戊寅四月，宋朝军队南迁并驻扎硇洲岛，供奉妈祖为护卫主神，尊称"军主"。宋亡后，宋军部分官兵留居硇洲，仍然供奉妈祖，沿袭至今。

根据村中老人的说法，岛上妈祖有三个神像，分别是大婆、二婆和三婆。大婆在镇上的庙宇，二婆没有庙宇，时时在不同家庭间流动，三婆即南村天后，在南村内有一个庙宇。

### 广兆泰山 {#taishan}

## 神明地位大小 {#god-range}

值得注意的是，村民会在神明之间区分地位的大小。我们一度猜测这是否从神明拥有的神物类型、数量判断，又或是通过神明的神格进行判断。例如拥有庙宇、香火更旺的神是否具有更高地位？或者神的地位是由其历史地位所决定的？

根据村中老人的说法，我将对神明地位大小的判断分成两个指标：1、绝对指标。包括神明受到信奉的规模及其历史身份；2、相对指标。神明所处的地域场合。

下面以广化马君、茅竹水仙大王、土地公、家神、南村天后与宋朝大臣作为例子进行说明。

**从绝对指标看**，作为境祖的广化马君比茅竹水仙大王、土地公和家神更大，原因一方面在于广化马君受到岛上许多村子的信奉，而茅竹水仙大王、土地公与家神只在西埠村内受到信奉。用村中老人的话说，大神与小神之间的关系如同乡长和村长。此为通过神明受到信奉的规模进行判断的指标。

> "你们村里的神，就是少神，就是村里，和干部一样，你是这个村的村长，我就是这个乡的乡长。乡长呢，就很多个村合起来就合一个乡，我就是这个乡的乡长，肯定我是大咯。"

另一方面，南村天后如果要和宋朝大臣比较大小，前者地位比后者更高，因为天后被视为玉帝的子嗣，而宋朝大臣只是一个将，归天后父亲管辖。用村长老人的话说，这如同省长的儿子来到区长的管理地，其身份仍然比之后者更高。此为通过神明的历史身份进行判断的指标。

**从相对指标看**，茅竹水仙大王和土地公在西埠村内是最大神明。他们被视为本村的村长、管理者。当村外的神明来到村中时，即使他们受到信奉的规模更大、历史身份地位也更加崇高，都要与本村的神明打个照面、知会一声。村中老人爱用现实中人与人的关系对此进行解释，认为村子属于本村神明的地盘，对村内大大小小的事情都了然于心，作为中央领导的广化马君来到村子时会受到基层民众的欢迎，但往往也会事先和村子通知一声，有什么事情也会首先向村长了解。

将茅竹水仙大王和土地公进一步对比，土地公的地位则更高，原因是茅竹水仙大王相对土地公而言，身份便从面对广化马君的本村村神转化为外村村神，不再是本村的村主。土地公是由玉帝直接派来管辖西埠村土地的神明，无法流动[^02-god-1]。

[^02-god-1]: 此处的"无法流动"与可以流动的水仙大王相对而言。需要指出的是，硇洲岛上存在不止一尊水仙大王，只是西埠村信奉的是"茅竹水仙大王"。

# 西埠村常见仪式 {#yishi}

由于神明信仰具有多元化和流动性的特点，村中与神明相关的仪式也具有好几种。以下是几种简单的分类：

1.  **请神仪式**

硇洲岛上神明常常处于流动的状态。其中，流动是指神随着时间流逝而在不同的村民家中落座。一年中神"居"无定所，若是境祖，本村人可以请去供奉，外村人也可以请去供奉，因此出现了一尊神一年在不同的村子里流动的现象。简而言之，请神即村民将神请到家里供奉。

现有研究表示，岛屿上的本土居民将神请到家中供奉与海上疍民拜神时将神请到船上相关。

2.  **接神仪式**

单独列出接神仪式，目的是为了区分村民主动请神与无庙宇的神明根据打飞轮到某户家庭之间的区别。两种仪式的目的、性质和具体过程会有所不同。例如请神往往是因为村民有喜事要办，带着较为明显和强烈的主观意愿；接神时往往是村民根据打飞后神的意愿做出的欢迎，是对传统与仪式的尊重和执行。

3.  **送神仪式**

神在家中落座具有时间限制。就西埠村而言，境祖停留一个月，村祖停留四个月。落座时间结束以后，村民便需要如同请神一般举行相关仪式将神从家中送出。

4.  **拜神仪式**

西埠村人拜神，除了本村的水仙公外，还会祭拜自己信仰（求愿时十分灵验）的神。南海观音是当地香火很旺的神，而香火旺的神大多都有庙宇，庙里一般有“守庙人”，平时主要负责打扫庙里的卫生，给前来祭拜的人上酒茶、放鞭炮，一个月还有几百块的工资。南海观音的庙宇里就有两位老人，平时两位老人就在庙里吃住。观音庙里还有摇签，香客如果需要摇签，还得捐功德钱。功德钱归两位老人所有。

5.  **还福仪式**

无论是在庙宇还是家中，村民们祭拜神明时提出的请求若在现实中成真，则需要准备祭品，举行还福仪式答谢神灵。（疑问点：大家集中还福？还是我可以自己单独去还福，不用像那天我观察到的一样集体举行隆重的仪式？）

此外，村民还会在还福仪式上选出福头。

6.  **游神仪式**

正月初八到元宵，硇洲岛上的村民会将神抬出来游街、游村，初八到十四是神在村里游，村民们会敞开大门，拿着香、鞭炮、元宝、香钱等神来，这一过程当地人称"等神"。十五是游元宵，这时是以村为单位，一村子的人将贡品统一摆在一个地方，等着神进村。

7.  **水仙公诞辰仪式**

茅竹水仙大王是西埠村的村祖，在硇洲岛上只受西埠村的供奉。每逢正月二十六，人们便从头人家中将茅竹水仙大王迎回庙宇，在诞辰前一日为神搭台唱戏。同时，作法师傅会通过茭杯/打飞来选出一年中的三个头人和三个看管神像财物的人。

## 请神仪式 {#qingshen}

请神时村民主动报名，走访村民问及为什么会供奉这个神时，西埠村的村民表示这是沿袭祖上供奉的习惯；另有一种说法是，供奉神明如同入会，需要交钱，然后登记造册。叹婆提及某年有人来收钱，入会得两块钱，少一块也不行，有些人家不想交，也就不交。

请神时村里会请师傅在报名的名单里筊杯，占卜出供奉的头人 ，同时还会占卜出管理有关神钱财的人。

根据村民提供的信息，师傅专门学习过相关知识。西埠村请马祖（广化马君）出庙时，在本村游神邀请的师傅与我们分享他有相关书籍，还加入了湛江市道教协会的的微信群。但村民提过有些年轻的三护请神和拜神的事宜还没有老人熟悉。

将神请到家里（将神送到下一户头人家）需要摆上贡品并放鞭炮，请三护来念文告诉神它将前往下一户人家坐，这个过程叫**起马**；头人只要将神送到村口，外村的下一位头人在村口等着，同时头人也会将记着神像身上配饰的本子交给下一位头人盘对，三护则同下一个头人一起回去念文，告诉神它这个月是在这一户人家坐，这个过程叫**落马**。

马祖（广化马君）交换的时间是农历十八。将神请到家的这段时间内，该户人家负责神像的清洁等一切事宜，每天早上、中午、傍晚都得上香。神像在家供奉时不可坐在供奉着它的大厅的正中间。供奉期间，神像如果遭到磕碰损坏，该户人家需要负全责；如果关于神的事情该头人无法解决，可以寻找其它村的头人商量。另外，如果家中有人去世，就不便将神请到家中。若是神在家中坐时有人去世，也得将神请到其他人家家中。

当神的诞辰来临时，村民会将神抬回其庙宇，并在庙宇前搭台唱戏给神听。戏团会主动到庙里揽生意，或者是这一年的头人一起负责联系戏团，而负责年头的头人在决定神的事宜时拥有最高决定权。唱戏的钱由三护占卜出的负责管理钱财的人向信奉该神的村民们收取。唱戏期间，头人们得看护神像，一般是在神的庙宇中住下，同时保证唱戏时没有孩童上台干扰，避免对神的不敬。

村民因结婚生子、建房入伙、发大财等原因想请神来庆祝时，可以到头人家将神请走，占卜好请神的日子，在神的庙宇或者是头人家的墙上贴请神的红纸，上面标有请神的日期、请神的村、贴的时间，一般是谁先贴谁就先请神，但得在请到神的当天晚上将神送回。

## 接神仪式 {#jieshen}

部分神明没有庙宇，总是在不同的村子或家庭中轮坐。例如西埠村信奉的境祖广化马君（另称马祖）便属于此类神明。

广化马君在一户人家中只坐一个月，从农历十八开始坐，下一个农历十八便轮到下一户人家。神明到哪一家坐由打飞结果决定，如果神通过打飞结果表示同意到该户人家坐，该户人家便会做好仪式、摆好酒席以欢迎神明的到来，表示欢喜。

即使是接神仪式，也充满讲究。上一个供奉神明的家庭需要选出一人，戴上用红布缠绕的香炉，一路跟着神像走到下一个需要供奉的村子。当护送神像来到村口时，会有人在前方敲锣打鼓，目的是通过声响将神“叫”回来。抵达村子后，除了上一位供奉神明的家庭，与其同村的人会离开，转由此次供奉神明的村子的村民们负责护送神像。

外来的神明到某一村子落座时，需要先去会见本村的神明以及供奉神明一家的祖先。马祖来到西埠村落座时，先是被抬去会见茅竹水仙大王，接着是土地公，最后才是供奉马祖的一家的祖先。一路上，信奉马祖的村民们会提前准备好香、鞭炮和纸钱，在年轻有力的男性们抬着马祖的轿子经过时献上香火、燃烧鞭炮与纸钱。西埠村村民还会靠近神像，拿出面额较小的纸钞塞进神像面前的小红袋内。

马祖到茅竹水仙大王、土地公与供奉人祖先所在老屋时都会停留一会儿，村民们基本遵循着“上香-烧纸-跪拜-递钱-放炮”几个步骤。会见过三位神祗后，马祖与送神人戴着的香炉被抬进接神人的房屋，而后送神人与接神人在神像面前举行交接香炉的仪式，接着让人将神像搬到边上的桌子，由师傅、送神人与接神人一起检查和清点神像财物，轿子则被抬进房屋的主厅。

直到财物检查完毕，神像才被搬回轿子内。此时，接神人一家会铺好草席向马祖祭拜。祭拜完毕后，接神一家集体到外面与参与仪式的村民们一起吃接神宴。

## 送神仪式 {#songshen}

送神仪式与接神仪式的过程相近。

马祖在离开西埠村前同样需要会见村中的神明，顺序与接神时一样，依次是茅竹水仙大王、土地公与供奉人一家的祖先。

村民们抬着马祖的轿子，一路上敲锣打鼓，供奉人一家由接神身份转化为送神身份，同样选出一名成员戴着用红布缠绕的香炉，一路跟着神像走过本村几位神明的所在地。锣声在前，鼓声、钹声、唢呐声在后，声响之后紧接着放鞭炮，路上时不时有村民靠近神像，上香烧纸。

将神像抬到村口时，下一个供奉马祖的村子里的村民已经在等待。西埠村村民送神队伍稍作停留，锣声、钹声与鼓声此起彼伏，抬着轿子的男性们上上下下抖动轿子，而后放下，由下一个村子的村民接替抬走神像。

无论是接神还是送神，神明来到村口时都会敲响锣声。一路上，神像完全由男性抬着走，如果村子距离较远，村民们会选择开着电动车跟随，随时替换感到疲惫的抬轿人。

在抬着神明赶往下一个村子的路途上，沿途经过的村子中时不时会有村民给神像上香、递纸钞、烧纸钱和放鞭炮。抬轿人们会在此时稍作停留。

来到下一个供奉神明的村子时，马祖同样会被抬到本村神明的庙宇。硇洲岛上基本每一座村子都有属于自己的土地公，但不一定有类似于西埠村信奉的茅竹水仙大王。会见本村村祖时，举行的仪式与西埠村接神时的仪式基本一样，马祖的轿子被放在本村村祖庙宇面前，两神面目相对，村民们给两神上香、烧纸钱、递纸钞、做祭拜和放鞭炮。

放鞭炮往往意味着仪式的尾声。

会见本村村祖结束后，马祖便被抬到此次供奉其神像的人家家庭。此次送神人与接神人同样先举行香炉的交接仪式，仪式结束后便将马祖的轿子抬进房子的正厅，神像则放到一边由师傅、送神人与接神人一起检查财物。

财物检查完毕后，接神人一家便在正厅内铺上草席做祭拜，接神宴也已经提前准备好，待最后的祭拜仪式结束后便与参与仪式的村民一同用餐。但对送神人而言，接神宴并非一定要参加，可以在完成神像交接的全部过程后离开。

## 拜神仪式 {#baishen}

拜神不同的情景时的贡品、祭拜方式存在差异。庙里拜神的情景大概可以分为：节日性拜神（包括神的诞辰）、求愿式拜神、日常拜神（不求愿也不过节），前两者的贡品一般是猪或者是一整只鸡、米饭、甜面、茶水、酒还有筷子，这些贡品必须是没有人动过、吃过，拜过某个神后的贡品不能与未拜的神的贡品混放在一起，西埠村人拜的南海观音是吃素菜、饭也是两碗倒扣合成一碗的饭。上完香烧完纸放完鞭炮后，香客会跪拜在上面求愿，叹婆在求愿时的念文如下：

>“去海……去时必顺利，做咪总是做虾做蟹（捕捞虾蟹的意思），吴妃珍的孩子……工作进步，工资提高，子孙读书清华北大，考上第一名……做啥、去到哪里、遇到什么人……吴妃珍，住在海边……船头，去就顺风，回就便利，保佑脚好手能，横财德财都速来……保佑吴妃珍男孙女孙、外孙、内孙都是孙，男子女子都是子，总得保佑，来来往往，路途路尾（大概是在外来来往往）来来去去，也望着你……让你子孙……”
>

后者的贡品一般是几个水果和布丁，上完香、放完鞭炮就走了。拜家神是指祭拜家里的祖先，一般是在祖先忌日、七月节拜祭，烧的是一种纸，在庙里烧的是元宝。

拜庙神时向神请的愿在未来结果如果令你满意的话，得回来还愿；还可以通过茭杯可以向神借钱，叹婆就向三婆借了两千块建房子，有一次叹婆上香时告诉三婆她要拿它一百块钱给拉电线的工人给鳏夫拉电，通过茭杯的方式知道三婆是否愿意。

## 还福仪式 {#huanfu}

西埠村的还福仪式在茅竹水仙大王的庙宇面前举行。

### 准备阶段 {#huanfu-zhunbei}

仪式开始以前，便有村民在庙宇前的树头下敲锣，目的是呼唤神明。另有两尊公和祖被抬到茅竹水仙大王的香炉面前，神像面前则有两张案台，一张案台摆放祭品，另一张案台摆放香炉。

村民们会提前来做祭拜，既拜公和祖，也拜茅竹水仙大王。祭拜的流程是“上香-烧纸钱-递纸钱-跪拜祈念-放炮”。在递纸钞的过程中，村民们会凑近神像低声说话，如同在观音堂与天后宫一般。

放过鞭炮以后，村民们有的可以选择离开，有的则会留下在旁边准备饭菜。

### 仪式阶段 {#huanfu-yishi}

在仪式正式开始前，村民们会将本村的村祖——也即茅竹水仙大王和土地公的神像搬到摆有祭品的案台上。

我在西埠村2024年1月4日（农历11月23日）观察到，除去两个公和祖的神像，案台上摆放的神像多达六具，分别是茅竹水仙大王、土地公、宋朝大臣、宋朝大臣的妻子以及主持仪式的师傅的随从。仪式准备开始时，村民们在六具神像面前摆了五碗米饭、五碗饭团、五碗甜面、五杯酒和五杯茶。

## 游神仪式 {#youshen}

1. 请神出

西埠村在正月有人家供奉广化马君（简称马祖）。在正月十二下午西埠村，村里将马祖、水仙公、土地公抬出来游神，马祖是供奉人（头人）家中请出来的。头人家人将贡品摆放好，贡品有茶酒、米饭、猪手（摆放顺序也是这般），贡品具体是什么、多少是由人的心意定，而马祖贡品不能是鸭。贡品摆好后、家里人到齐后就上香行拜、捐功德钱、烧元宝放鞭炮。头人及其家人在地上铺上草席，和请来的三护一起跪在上面，三护念一段文并茭杯，文的大概意思是告诉马祖先跪拜的人姓甚名谁，并且告诉马祖要游神，子孙也将出游。念完后，头人家人（不知是不是头人本人）将马祖从神龛里抱出，有力的男人将马祖的神龛搬到推车上，然后再将马祖放到神龛里。马祖出行有其规模，两位拿着写着“清道”的字走在前面，两位拿着写有“廣化马君”的横幅跟在后面，有队员人数是单数组成的彩旗队，还有专业的敲锣打鼓队，装有乐器的车顶盖也是有着“廣化马君”的字。将马祖抬到戏台前的土地公庙前，马祖到时水仙公、土地公已到，两尊神是坐在四角桌上，上面放着一些水果，三神一同受村民的香火。

2. 抬神游村
村民上了香后就抬着水仙公、马祖在村里游。水仙公是抱在手上游，马祖是坐着轿子，两尊神是在队伍的后面。村民打开着门、手里拿着鞭炮、元宝、几块钱等着神到，神到时，村民上香、跪拜、烧元宝，放鞭炮，一般村民都叫抬神的人等鞭炮放完才走。游神的路线一般是方便队伍游完村里，不会绕太多圈子。在游神的过程中也会到土地公的“露天庙”里相会。沿着游神路线，因水仙公要坐的那户人家的家在前面，它就回去那户人家坐，不参与接下来的游神。

元宵节游神

元宵节南港村下的几个自然村有名的神参与游神，是以南角尾村为起点开始游，村里的老人表示游神的起点就看祖妈（不知是二婆还是三婆）是在哪个村坐就从哪个村开始，剩下的路线就按着游神队伍方便走，少绕弯路的法子走。我们到南角尾村时，三婆、在西埠村待过的马祖、洪拱马祖、调但王夫妇、文天祥等七个神都到了，二婆还没有来。我们在来的路上看到西埠村的村民将马祖推出来要参加游神，到村口时就有货车将马祖接走，村民紧跟在后面。二婆到时队伍就出发了，走在前头的是二婆，再到三婆，其它的六个神在后面。队伍前头是一位敲锣的，两位孩子拿着写有“清道”的白棋缓缓跟着，在后面的便是二婆的出行规模。此次游神只有二婆、三婆有出行规模，两位神的规模除了仪仗、四位随行侍女的颜色不同外，没有其它不同的地方。两位拿着写有祖妈的道号的精美横幅、两位举着仪仗扇、两位挑着小香炉，香炉的前头绑着红绳布袋方便村民捐钱，四位美貌着艳丽服饰走在祖妈轿子前，二婆的四位侍女是游到第二村时才到的，还有几支专业的锣鼓队跟着，其余的神就是坐在神龛里，神的头人跟随在旁边。游神队伍进村后，可以看到村民在空旷的地方几张桌子放着全村人的贡品，待各位神的轿子都排成一条队时，村民就上前上香，捐功德钱。观察到每位神的神像前都有一个红色的袋子方便村民上香时捐功德钱。给两位妈祖的功德钱除了神像前的那个袋子外，还得往香炉另一端的袋子、轿子上挂着的红袋子捐钱。放在桌子前的贡品站近点看，可以了解到一张桌子上有好张装着鸡的大钢盘，盘里也有五花肉，有些盘里装的是鱿鱼，桌上还有筷子插在饭中央的米饭、快放在碗上的面条、酒还有胡萝卜、葱。红色袋子装着苹果、沃橘、饼干、西柚、各种糖果，有些袋子还装有烧的元宝和短鞭炮。上完香后人们将元宝放在一废弃的大锅里烧，烧完后就跪拜在草席上，有些人在草席上行三跪九拜后向各位神求愿，但最长的不超过三分钟，有些人三跪九拜便起身。等差不多都上完香后，村民就集中放长几米的鞭炮，南角尾村放鞭炮的同时也放烟花，因等神的地方小，放炮时烟将周围的一切都遮住了，连距离一米内的桌上贡品都看不清。鞭炮放完后游神的队伍就离开前往下一村。

下一个村子是德斗村，在路上有一位婶从路旁走出来，跪拜在二婆的轿子前，一边拜嘴里还念着什么，随行的一位叔说路上有人想拜神队伍都可以停下来让她拜。当队伍从德斗村口走到村里几百米时，队伍就停了下来，发现队头扛着二婆横幅的两位婶和德斗村的村长争论起来了，站近了听后了解到该村的祖头没有在村口上香放炮，其中的一位说不用祖头弄，她们自己在村口上香放炮也可以，和村长争论的一位婶说这不对，然后三人就争论了一段时间，祖头来了后队伍才调头往村口旁的土地公庙。问了游神队伍的叔和婶后了解到因德斗村的村口有土地公在，众神想进村得先拜过土地公，村民们的意思是土地公是村主，进人家的村得和人家打个招呼。一些是武将的神在前往土地公庙时抬轿的人会将轿子上下颠，这个表示的是武将的上马动作。待众神都派整齐后就开始上香烧元宝放鞭炮，鞭炮声完后队伍就走了。德斗村有四个土地公，四个土地公都相会完后队伍才进村到村民等神处。德斗村是在村的广场摆桌，村民很多，一拐进来就看到乌黑黑的人群拿着香等神来。德斗村的贡品饭、茶酒、面条（干的）也和南角尾村一样的摆着，而德斗村的肉类大部分是烤乳猪，是村里几户人或者一户人奉上一只烤乳猪，猪的头上还插红纸包着炳的小刀，也有葱、五花肉、猪手猪肺和元宝，水果有苹果、沙糖桔、橙子，有一桌还放了冰糖和红枣在碟子里。德斗村的人比较多，村民是拿着香排队给神上香，在来德斗村的路上，有其它的两位神也加入了游神队伍。拜神的步骤基本和南角尾村一样，德斗村老人、孩子多，就将草席铺在了好多地方，人来人往，专业的声乐队也在继续干活，现场还可以听到家长叫孩子赶紧来拜神的声音，现场因人多看起来很乱，但是每个人又很秩序地排着队拜，一个神接着一个神的拜，手里拿着大把的一块钱，人在后面一个接着一个拜神。也是等人拜神拜的差不多时，就准备放鞭炮，德斗村就只放鞭炮，但是鞭炮很长，长的有八米多。

## 水仙公诞辰仪式 {#shuixiangon}

# 神明故事 {#god-story}
